theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding"]

key = "key.toml"